# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ee9d7904fa53a560bc6efd3699a2ce87f6b40b1e378b7ce8f9e7a638474d39c3161010aaa4c22b23810002b8ede3545d00dc855d6d021983f34004cd5d6e404

test:
  secret_key_base: 48a2a29c2efc5e20638a9886bd17d5475c5e8910c5afa6b137df8216846b0a73d456a741b9a7bd8b534fa8dda674f95b023982af6396b8460cc257ead445b7a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
